-- ============================================================
-- Script DDL completo - Agenda Médica (MySQL)
-- Gerado a partir do Diagrama Entidade-Relacionamento
-- ============================================================

-- Remove as tabelas se já existirem (ordem inversa das dependências)
DROP TABLE IF EXISTS AGENDAMENTO;
DROP TABLE IF EXISTS PLANO;
DROP TABLE IF EXISTS PROFISSIONAL;
DROP TABLE IF EXISTS ESPECIALIDADE;
DROP TABLE IF EXISTS BENEFICIARIO;
DROP TABLE IF EXISTS PROCEDIMENTO;
DROP TABLE IF EXISTS CONVENIO;
DROP TABLE IF EXISTS CLINICA;
DROP TABLE IF EXISTS SALA;
DROP TABLE IF EXISTS CID;
DROP TABLE IF EXISTS TIPO_AGENDAMENTO;
DROP TABLE IF EXISTS USUARIO;

-- ============================================================
-- Tabelas independentes
-- ============================================================

CREATE TABLE PROFISSIONAL (
    PROF_ID             INT             NOT NULL,
    PROF_NOME           VARCHAR(150)    NOT NULL,
    PROF_CONSELHONUM    VARCHAR(20),
    PROF_CONSELHOUF     VARCHAR(2),
    PROF_SEXO           VARCHAR(1),
    PROF_STATUS         INT,
    PRIMARY KEY (PROF_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE ESPECIALIDADE (
    ESP_ID              INT             NOT NULL,
    ESP_DESCRICAO       VARCHAR(100)    NOT NULL,
    ESP_CMED            INT,
    PRIMARY KEY (ESP_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE BENEFICIARIO (
    BENEF_ID            BIGINT             NOT NULL,
    BENEF_NOME          VARCHAR(150)    NOT NULL,
    BENEF_DTNASC        DATETIME,
    BENEF_CPF           VARCHAR(11),
    BENEF_SEXO          VARCHAR(1),
    BENEF_NUMCARTEIRA   VARCHAR(30),
    PRIMARY KEY (BENEF_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE PROCEDIMENTO (
    TBLPROCED_ID        INT             NOT NULL,
    PROC_CODIGO         INT,
    PROC_DESCRICAO      VARCHAR(200),
    AGP_VALOR           DECIMAL(10,2),
    PRIMARY KEY (TBLPROCED_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE CONVENIO (
    CONV_ANS            VARCHAR(20)     NOT NULL,
    CONV_SIGLA          VARCHAR(30),
    CONV_CNPJ           VARCHAR(14),
    PRIMARY KEY (CONV_ANS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE CLINICA (
    CLI_ID              INT             NOT NULL,
    CLI_CORPORATIVO     INT,
    PRIMARY KEY (CLI_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE SALA (
    SALA_ID             INT             NOT NULL,
    PRIMARY KEY (SALA_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE CID (
    TBL_IDCID           INT             NOT NULL,
    CID_ID              INT,
    PRIMARY KEY (TBL_IDCID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE TIPO_AGENDAMENTO (
    TPA_ID              INT             NOT NULL,
    TPA_DESCRICAO       VARCHAR(100),
    PRIMARY KEY (TPA_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE USUARIO (
    USER_ID             INT             NOT NULL,
    NOME                VARCHAR(150),
    PRIMARY KEY (USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ============================================================
-- Tabela dependente de CONVENIO
-- ============================================================

CREATE TABLE PLANO (
    PLANO_ID            INT             NOT NULL,
    PLANO_DESCRICAO     VARCHAR(100),
    CONV_ANS            VARCHAR(20),
    PRIMARY KEY (PLANO_ID),
    CONSTRAINT FK_PLANO_CONVENIO
        FOREIGN KEY (CONV_ANS)
        REFERENCES CONVENIO (CONV_ANS)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ============================================================
-- Tabela central de AGENDAMENTO
-- ============================================================

CREATE TABLE AGENDAMENTO (
    AG_ID                   INT             NOT NULL,
    PROF_ID                 INT,
    ESP_ID                  INT,
    BENEF_ID                BIGINT,
    TBLPROCED_ID            INT,
    PLANO_ID                INT,
    CLI_ID                  INT,
    SALA_ID                 INT,
    TPA_ID                  INT,
    TBL_IDCID               INT,
    USER_ID                 INT,
    DTHORAAGENDA            DATETIME,
    AG_STATUSAGENDAMENTO    VARCHAR(1),
    PRIMARY KEY (AG_ID),

    -- Relacionamentos (1:N)
    CONSTRAINT FK_AGENDAMENTO_PROFISSIONAL
        FOREIGN KEY (PROF_ID)
        REFERENCES PROFISSIONAL (PROF_ID)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,

    CONSTRAINT FK_AGENDAMENTO_ESPECIALIDADE
        FOREIGN KEY (ESP_ID)
        REFERENCES ESPECIALIDADE (ESP_ID)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,

    CONSTRAINT FK_AGENDAMENTO_BENEFICIARIO
        FOREIGN KEY (BENEF_ID)
        REFERENCES BENEFICIARIO (BENEF_ID)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,

    CONSTRAINT FK_AGENDAMENTO_PROCEDIMENTO
        FOREIGN KEY (TBLPROCED_ID)
        REFERENCES PROCEDIMENTO (TBLPROCED_ID)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,

    CONSTRAINT FK_AGENDAMENTO_PLANO
        FOREIGN KEY (PLANO_ID)
        REFERENCES PLANO (PLANO_ID)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,

    CONSTRAINT FK_AGENDAMENTO_CLINICA
        FOREIGN KEY (CLI_ID)
        REFERENCES CLINICA (CLI_ID)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,

    CONSTRAINT FK_AGENDAMENTO_SALA
        FOREIGN KEY (SALA_ID)
        REFERENCES SALA (SALA_ID)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,

    CONSTRAINT FK_AGENDAMENTO_TIPO_AGENDAMENTO
        FOREIGN KEY (TPA_ID)
        REFERENCES TIPO_AGENDAMENTO (TPA_ID)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,

    CONSTRAINT FK_AGENDAMENTO_CID
        FOREIGN KEY (TBL_IDCID)
        REFERENCES CID (TBL_IDCID)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,

    CONSTRAINT FK_AGENDAMENTO_USUARIO
        FOREIGN KEY (USER_ID)
        REFERENCES USUARIO (USER_ID)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Fim do script